FROM python:3.11-slim

RUN apt-get update && apt-get install -y wget \
    && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /employee_app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY e2e ./e2e

WORKDIR /employee_app/e2e
CMD ["behave"]
